baseURL = "https://alpinswheelteam.fr/"
languageCode = "fr-fr"
title = "Alpin's Wheel Team"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

[[menu.main]]
    name = "L'équipe"
    url = "/membres/"
    weight = 2

[[menu.main]]
    name = "Partenaires"
    url = "/partenaires/"
    weight = 3


[[menu.main]]
    name = "Chrono du Vercors"
    url = "/chrono/"
    weight = 4

[[menu.main]]
    name = "Liens utiles"
    url = "/liens/"
    weight = 5


[params]
  google_analytics_id=""

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Alpin's Wheel Team est un club cycliste de la région de Grenoble."
    meta_og_title = "Alpin's Wheel Team"
    meta_og_type = "website"
    meta_og_url = "https://alpinswheelteam.fr"
    meta_og_image = "https://alpinswheelteam.fr/images/alpinswheelteam.png"
    meta_og_description = "Alpin's Wheel Team est un club cycliste de la région de Grenoble."

  [params.logo]
      mobile = "/images/alpinswheelteam.png"
      standard  = "/images/alpinswheelteam.png"
      right = "/images/aw.webp"

